version: 2
jobs:  
  build_ckan_28:
    working_directory: ~/ckanext-datagovcatalog
    machine:
      image: circleci/classic:201708-01
    environment:
      CKANVERSION=2.8
    steps:
      - checkout
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_ckan_28

