name: Tests
on: [push]

jobs:
  lint-test:
    name: Lint + Test
    uses: gsa/data.gov/.github/workflows/ckan-test.yml@ckan-211-test
    with:
      ext_name: datagovcatalog
      plugins: envvars harvest ckan_harvester datagovcatalog
    secrets: inherit
